In [1]:
import numpy as np
import pandas as pd
from datetime import datetime

In [2]:
data_folder = '../data/julie_bch_obs/'
df_set_1 = pd.read_csv(f"{data_folder}2023-01-01_2023-12-31_hourly[UTC]_set1.csv")
df_set_2 = pd.read_csv(f"{data_folder}2023-01-01_2023-12-31_hourly[UTC]_set2.csv")
df_set_3 = pd.read_csv(f"{data_folder}2023-01-01_2023-12-31_hourly[UTC]_set3.csv")

In [3]:
print(df_set_1.columns.values)
print(df_set_2.columns.values)
print(df_set_3.columns.values)

['valid[UTC]' 'ALU_Precip[mm]' 'ALU_AirTemp[degC]' 'ASH_Precip[mm]'
 'ASH_AirTemp[degC]' 'BAR_Precip[mm]' 'BAR_AirTemp[degC]' 'BCK_Precip[mm]'
 'BCK_AirTemp[degC]' 'BGP_Precip[mm]' 'BGP_AirTemp[degC]' 'CDW_Precip[mm]'
 'CDW_AirTemp[degC]' 'CLO_Precip[mm]' 'CLO_AirTemp[degC]' 'CMX_Precip[mm]'
 'CMX_AirTemp[degC]' 'DAI_Precip[mm]' 'DAI_AirTemp[degC]' 'DLU_Precip[mm]'
 'DLU_AirTemp[degC]' 'EAC_Precip[mm]' 'EAC_AirTemp[degC]' 'ECL_Precip[mm]'
 'ECL_AirTemp[degC]' 'FAQ_Precip[mm]' 'FAQ_AirTemp[degC]' 'FIN_Precip[mm]'
 'FIN_AirTemp[degC]' 'FLL_Precip[mm]' 'FLL_AirTemp[degC]']
['valid[UTC]' 'GOC_Precip[mm]' 'GOC_AirTemp[degC]' 'GOL2_Precip[mm]'
 'GOL2_AirTemp[degC]' 'HFF_Precip[mm]' 'HFF_AirTemp[degC]'
 'HRN_Precip[mm]' 'HRN_AirTemp[degC]' 'HUR2_Precip[mm]'
 'HUR2_AirTemp[degC]' 'ING_Precip[mm]' 'ING_AirTemp[degC]'
 'JHL_Precip[mm]' 'JHL_AirTemp[degC]' 'KAA_Precip[mm]' 'KAA_AirTemp[degC]'
 'KWA_Precip[mm]' 'KWA_AirTemp[degC]' 'MCQ_Precip[mm]' 'MCQ_AirTemp[degC]'
 'MIS_Precip[mm]' 'MIS_AirTemp[degC]' 'MLP_Precip[mm]' 'MLP_AirTemp[degC]'
 'MOL_Precip[mm]' 'MOL_AirTemp[degC]' 'MOR_Precip[mm]' 'MOR_AirTemp[degC]'
 'NDE_Precip[mm]' 'NDE_AirTemp[degC]' 'NTY_Precip[mm]' 'NTY_AirTemp[degC]'
 'PAR_Precip[mm]' 'PAR_AirTemp[degC]' 'PKM_Precip[mm]' 'PKM_AirTemp[degC]'
 'PYN_Precip[mm]' 'PYN_AirTemp[degC]']
['valid[UTC]' 'QIN2_Precip[mm]' 'QIN2_AirTemp[degC]' 'REC_Precip[mm]'
 'REC_AirTemp[degC]' 'RST_Precip[mm]' 'RST_AirTemp[degC]'
 'SBD2_Precip[mm]' 'SBD2_AirTemp[degC]' 'SHH_Precip[mm]'
 'SHH_AirTemp[degC]' 'STV_Precip[mm]' 'STV_AirTemp[degC]' 'UCE_Precip[mm]'
 'UCE_AirTemp[degC]' 'WAH_Precip[mm]' 'WAH_AirTemp[degC]' 'WJR_Precip[mm]'
 'WJR_AirTemp[degC]' 'WOL_Precip[mm]' 'WOL_AirTemp[degC]' 'WON_Precip[mm]'
 'WON_AirTemp[degC]' 'WZA_Precip[mm]' 'WZA_AirTemp[degC]' 'YGS_Precip[mm]'
 'YGS_AirTemp[degC]' 'YLW_Precip[mm]' 'YLW_AirTemp[degC]' 'YRV_Precip[mm]'
 'YRV_AirTemp[degC]' 'YXS_Precip[mm]' 'YXS_AirTemp[degC]' 'YYD_Precip[mm]'
 'YYD_AirTemp[degC]' 'YZY_Precip[mm]' 'YZY_AirTemp[degC]']

In [4]:
print(df_set_1.shape)
print(df_set_1.value_counts())
print('\n')
print(df_set_2.shape)
print(df_set_2.value_counts())
print('\n')
print(df_set_3.shape)
print(df_set_3.value_counts())

(8760, 31)
valid[UTC]           ALU_Precip[mm]  ALU_AirTemp[degC]  ASH_Precip[mm]  ASH_AirTemp[degC]  BAR_Precip[mm]  BAR_AirTemp[degC]  BCK_Precip[mm]  BCK_AirTemp[degC]  BGP_Precip[mm]  BGP_AirTemp[degC]  CDW_Precip[mm]  CDW_AirTemp[degC]  CLO_Precip[mm]  CLO_AirTemp[degC]  CMX_Precip[mm]  CMX_AirTemp[degC]  DAI_Precip[mm]  DAI_AirTemp[degC]  DLU_Precip[mm]  DLU_AirTemp[degC]  EAC_Precip[mm]  EAC_AirTemp[degC]  ECL_Precip[mm]  ECL_AirTemp[degC]  FAQ_Precip[mm]  FAQ_AirTemp[degC]  FIN_Precip[mm]  FIN_AirTemp[degC]  FLL_Precip[mm]  FLL_AirTemp[degC]
2023-01-01 00:00:00  0.1             4.9                0.0             4.0                0.0             -3.1               0.0             4.2                0.0             -2.3               0.7             5.7                0.1             6.6                0.0             6.3                0.0             1.8                0.0             -4.1               0.2             -6.5               0.0             3.2                0.0             0.3                0.0             -5.9               0.3             -0.1                 1
2023-09-01 10:00:00  0.0             14.5               0.2             13.4               0.1              7.3               0.0             9.3                0.2              9.2               0.0             13.0               0.0             13.4               0.1             12.6               0.1             10.8               0.4              8.5               1.1              6.1               0.0             10.6               0.5             13.1               0.0              5.1               0.3              12.0                1
2023-09-01 04:00:00  0.0             15.6               0.0             18.9               0.4              8.1               0.0             12.3               0.0              10.4              0.0             15.5               0.0             16.2               0.0             16.0               0.0             14.4               0.0              6.5               0.1              6.5               0.0             14.0               0.0             13.5               0.0              12.9              0.1              12.4                1
2023-09-01 05:00:00  0.0             15.5               0.0             17.6               0.2              8.0               0.0             11.7               0.0              10.0              0.0             14.9               0.0             15.2               0.0             15.0               0.0             13.1               0.0              7.0               0.1              6.6               0.0             13.1               0.0             13.3               0.0              10.6              0.0              12.0                1
2023-09-01 06:00:00  0.0             15.9               0.0             16.1               0.0              7.8               0.0             11.6               0.0              10.0              0.0             14.2               0.0             14.8               0.0             14.2               0.0             12.2               0.0              7.7               0.1              6.5               0.0             12.3               0.0             13.3               0.0              8.9               0.0              11.9                1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ..
2023-05-02 10:00:00  0.7             8.5                0.2             7.8                0.0              1.8               0.0             5.0                0.0              2.1               0.1             8.4                0.3             7.9                0.0             6.8                0.1             8.3                0.6              4.0               0.0              9.1               0.0             7.2                0.0             8.3                0.0             -0.9               0.3              2.5                 1
2023-05-02 09:00:00  0.0             8.5                0.0             8.3                0.0              2.0               0.0             5.4                0.0              1.7               0.0             8.5                0.0             8.5                0.0             7.5                0.0             10.0               0.0              4.2               0.0              9.8               0.0             7.7                0.0             8.7                0.0              0.1               0.0              2.6                 1
2023-05-02 08:00:00  0.0             8.8                0.0             8.6                0.0              1.9               0.0             5.6                0.0              2.7               0.0             9.2                0.0             8.9                0.0             7.8                0.0             9.1                0.0              4.8               0.0              9.8               0.0             6.8                0.0             9.2                0.0              1.6               0.0              3.3                 1
2023-05-02 07:00:00  0.0             9.1                0.0             9.4                0.0              2.5               0.0             6.3                0.0              2.9               0.0             9.2                0.0             9.6                0.0             8.6                0.0             10.2               0.1              4.6               0.0              9.5               0.0             6.6                0.0             10.1               0.0              3.1               0.0              3.6                 1
2023-12-31 23:00:00  0.4             9.6                0.0             6.1                0.0             -1.0               0.0             4.8                0.1             -0.3               0.0             7.0                0.0             7.4                0.0             7.2                0.0             5.4                0.0             -2.4               0.1             -3.8               0.0             2.9                0.0             1.7                0.0             -4.0               0.0              0.6                 1
Name: count, Length: 8760, dtype: int64


(8760, 39)
valid[UTC]           GOC_Precip[mm]  GOC_AirTemp[degC]  GOL2_Precip[mm]  GOL2_AirTemp[degC]  HFF_Precip[mm]  HFF_AirTemp[degC]  HRN_Precip[mm]  HRN_AirTemp[degC]  HUR2_Precip[mm]  HUR2_AirTemp[degC]  ING_Precip[mm]  ING_AirTemp[degC]  JHL_Precip[mm]  JHL_AirTemp[degC]  KAA_Precip[mm]  KAA_AirTemp[degC]  KWA_Precip[mm]  KWA_AirTemp[degC]  MCQ_Precip[mm]  MCQ_AirTemp[degC]  MIS_Precip[mm]  MIS_AirTemp[degC]  MLP_Precip[mm]  MLP_AirTemp[degC]  MOL_Precip[mm]  MOL_AirTemp[degC]  MOR_Precip[mm]  MOR_AirTemp[degC]  NDE_Precip[mm]  NDE_AirTemp[degC]  NTY_Precip[mm]  NTY_AirTemp[degC]  PAR_Precip[mm]  PAR_AirTemp[degC]  PKM_Precip[mm]  PKM_AirTemp[degC]  PYN_Precip[mm]  PYN_AirTemp[degC]
2023-01-01 00:00:00  0.1             0.2                0.4              -0.8                0.0             -21.7              0.0             -8.9               0.0              0.3                 0.0             -6.1               0.0             -9.2               0.3             1.1                0.0             -12.4              0.0             -6.3               0.1             -4.7               0.1             -3.3               0.3             -6.3               0.0             -3.7               0.0             1.1                0.2             -4.7               0.0             -3.3               0.7             -4.9               0.0             -6.6                 1
2023-09-01 10:00:00  0.0             9.6                0.5               12.2               0.0              8.6               0.0              3.0               0.0              9.4                 0.0              7.9               0.1              4.1               0.1             12.5               0.0              8.0               0.0              4.3               0.0              6.0               0.0              6.3               0.3              5.8               0.4              7.1               1.0             12.6               0.2              5.8               0.0              6.9               0.7              5.7               0.1              9.9                 1
2023-09-01 04:00:00  0.0             10.7               0.0               13.5               0.0              16.1              0.0              5.7               0.0              11.3                0.0              15.7              0.0              6.0               0.2             14.1               0.0              8.7               0.0              8.2               0.0              5.9               0.1              6.5               0.4              6.5               0.0              8.0               0.1             13.6               0.0              5.5               0.0              11.3              0.0              6.2               0.0              12.2                1
2023-09-01 05:00:00  0.0             10.4               0.0               13.1               0.0              14.1              0.0              4.3               0.0              10.5                0.0              13.0              0.0              3.9               0.2             13.7               0.0              8.4               0.0              6.1               0.0              5.8               0.0              5.9               0.2              6.4               0.0              7.1               0.4             13.5               0.0              5.3               0.0              9.8               0.0              6.2               0.0              9.1                 1
2023-09-01 06:00:00  0.0             10.5               0.0               12.7               0.0              12.5              0.0              3.8               0.0              10.1                0.0              10.4              0.0              2.9               0.0             13.4               0.0              7.8               0.0              4.6               0.6              5.8               0.0              6.0               0.0              6.3               0.0              7.4               0.5             13.6               0.0              5.7               0.0              9.3               0.0              6.2               0.0              7.9                 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ..
2023-05-02 10:00:00  0.6             4.3                0.2              -1.1                0.0              4.9               0.6             -2.3               0.0              5.9                 0.0             -0.4               0.0             -3.5               0.0             10.7               0.0              1.8               0.2             -2.7               0.1              3.6               0.1              1.5               0.5              6.0               0.0              8.4               0.0             7.8                0.2              2.8               0.0              0.9               0.0              7.2               0.1              3.4                 1
2023-05-02 09:00:00  0.0             3.0                0.0              -0.6                0.0              5.6               0.0             -1.9               0.0              6.2                 0.0              1.1               0.0             -3.0               0.0             11.2               0.0              1.8               0.0             -2.2               0.0              3.7               0.0              1.3               0.0              6.5               0.0              7.7               0.0             8.4                0.0              2.6               0.0              1.9               0.0              7.1               0.0              3.5                 1
2023-05-02 08:00:00  0.0             4.4                0.0               0.1                0.0              6.9               0.0             -1.5               0.0              6.6                 0.0              2.1               0.0             -2.2               0.0             11.9               0.0              2.4               0.0             -1.5               0.0              3.2               0.0              1.7               0.0              7.8               0.0              7.9               0.0             9.1                0.0              2.9               0.0              2.8               0.0              6.9               0.0              3.9                 1
2023-05-02 07:00:00  0.0             3.9                0.0               0.9                0.0              8.3               0.0             -0.7               0.0              6.9                 0.0              4.1               0.0             -1.2               0.0             12.7               0.0              2.7               0.0             -0.2               0.0              3.4               0.0              3.8               0.0              7.6               0.0              9.3               0.0             10.0               0.0              3.3               0.0              4.3               0.0              7.4               0.0              6.0                 1
2023-12-31 23:00:00  0.0             2.8                0.0               0.3                0.0             -6.5               0.0             -2.7               0.0              3.1                 0.0             -4.0               0.1             -5.2               0.0             0.6                0.0             -5.7               0.0             -0.3               0.0             -2.7               0.0             -1.2               0.0             -3.3               0.3             -1.4               0.0             1.8                0.0             -3.2               0.0              0.6               0.0             -3.1               0.0             -2.6                 1
Name: count, Length: 8760, dtype: int64


(8760, 37)
valid[UTC]           QIN2_Precip[mm]  QIN2_AirTemp[degC]  REC_Precip[mm]  REC_AirTemp[degC]  RST_Precip[mm]  RST_AirTemp[degC]  SBD2_Precip[mm]  SBD2_AirTemp[degC]  SHH_Precip[mm]  SHH_AirTemp[degC]  STV_Precip[mm]  STV_AirTemp[degC]  UCE_Precip[mm]  UCE_AirTemp[degC]  WAH_Precip[mm]  WAH_AirTemp[degC]  WJR_Precip[mm]  WJR_AirTemp[degC]  WOL_Precip[mm]  WOL_AirTemp[degC]  WON_Precip[mm]  WON_AirTemp[degC]  WZA_Precip[mm]  WZA_AirTemp[degC]  YGS_Precip[mm]  YGS_AirTemp[degC]  YLW_Precip[mm]  YLW_AirTemp[degC]  YRV_Precip[mm]  YRV_AirTemp[degC]  YXS_Precip[mm]  YXS_AirTemp[degC]  YYD_Precip[mm]  YYD_AirTemp[degC]  YZY_Precip[mm]  YZY_AirTemp[degC]
2023-01-01 00:00:00  0.0              1.4                 0.0             2.0                0.0             -1.1               0.0              1.5                 0.0             2.6                0.1             0.5                0.0             4.2                0.0             2.2                0.0             3.7                0.0             -0.6               0.0             -8.2               0.2             6.9                0.0             -4.5               0.0             1.5                0.1             0.5                0.0             -1.3               0.0             -3.0               0.0             -4.9                 1
2023-09-01 17:00:00  0.1              15.9                0.0             14.4               0.0              14.4              0.0              15.3                0.0             16.7               0.0             17.1               0.0             16.4               0.0             19.0               0.0             14.3               0.0              14.0              0.0              16.2              0.0             19.1               0.0              10.6              0.0             15.0               0.0             15.6               0.0              10.9              0.0              8.9               0.0              10.6                1
2023-09-01 11:00:00  0.0              7.0                 0.0             7.8                0.0              12.4              0.0              9.6                 0.0             14.0               0.0             12.2               0.0             10.2               0.0             10.5               0.0             12.5               0.0              11.5              0.0              9.1               0.0             17.8               0.0              3.7               0.0             11.6               0.0             12.9               0.0              6.8               0.0              8.6               0.0              5.7                 1
2023-09-01 12:00:00  0.0              6.5                 0.0             7.4                0.0              12.2              0.0              9.0                 0.0             13.7               0.0             12.2               0.0             11.2               0.0             10.4               0.0             12.2               0.0              11.6              0.0              8.7               0.0             17.1               0.0              4.3               0.0             12.5               0.0             12.7               0.0              4.8               0.0              7.7               0.0              5.1                 1
2023-09-01 13:00:00  0.0              6.2                 0.0             7.2                0.0              12.2              0.0              8.4                 0.0             13.3               0.0             12.4               0.0             10.0               0.0             10.4               0.0             12.4               0.0              11.4              0.0              8.5               0.0             17.2               0.0              3.7               0.0             13.4               0.0             12.9               0.0              4.8               0.0              6.9               0.0              5.4                 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ..

In [5]:
print(df_set_1['valid[UTC]'].values[0]) # [11:13]
print(len(df_set_1))

2023-01-01 00:00:00
8760

In [6]:
stations = pd.read_csv(f"{data_folder}station_metadata.csv")
stations.head(10)

,station_no,station_name,site_no,station_longitude,station_latitude,station_elevation
0,85A,85th Avenue,07F,NaN,NaN,NaN
1,YXX,Abbotsford A,08M,-122.360000,49.025278,59.0
2,1F01A,Aberdeen Lk SC,08L,-119.053293,50.146514,1262.0
3,1E07,Adams R SC,08L,-119.426400,51.583611,1720.0
4,1100120,Agassiz CDA,08M,-121.759722,49.242500,15.0
5,WZA,Agassiz CS,08M,-121.750000,49.233333,19.0
6,AKN,Aiken Lk,07E,-125.741667,56.436667,970.0
7,05AD802,Akamina Pass,05A,NaN,NaN,NaN
8,AKM,Akamina Pass 2,05A,-114.053497,49.027307,1809.0
9,AKI,Akie R nr 760 M Contour,07E,-124.904244,57.191192,760.0

In [7]:
stations[stations.station_no=='FAQ']

,station_no,station_name,site_no,station_longitude,station_latitude,station_elevation
313,FAQ,Fauquier Water Treatment Plant,08N,-118.074228,49.864182,519.0

In [8]:
stations_set_1 = [x.split('_')[0] for x in df_set_1.columns if len(x.split('_'))==2]
stations_set_2 = [x.split('_')[0] for x in df_set_2.columns if len(x.split('_'))==2]
stations_set_3 = [x.split('_')[0] for x in df_set_3.columns if len(x.split('_'))==2]
stations_list = stations_set_1 + stations_set_2 + stations_set_3
print(len(stations_list))
print(len(set(stations_list)))

104
52

In [9]:
df = pd.DataFrame(columns=['UTC_DATE', 'x', 'y', 'STN_ID', 'TEMP', 'PRECIP_AMOUNT'])
init_hours = [0, 6, 12, 18]
count = 0
for df_data in [df_set_1, df_set_2, df_set_3]:
    stations_list = list(set([x.split('_')[0] for x in df_data.columns if len(x.split('_'))==2]))
    for station in stations_list:
        precip_amount = df_data[f"{station}_Precip[mm]"].rolling(6).sum()

        concat = pd.DataFrame({
            'UTC_DATE': df_data['valid[UTC]'],
            'x': stations[stations.station_no==station]['station_longitude'].values[0],
            'y': stations[stations.station_no==station]['station_latitude'].values[0],
            'STN_ID': station,
            'TEMP': df_data[f"{station}_AirTemp[degC]"],
            'PRECIP_AMOUNT': precip_amount,
        })
        print(' - concat : ', len(concat))
        dt = concat.UTC_DATE.apply(lambda x :  datetime.strptime(x, '%Y-%m-%d %H:%M:%S'))
        init_mask = dt.apply(lambda x: x.hour in init_hours)

        concat = concat[init_mask]
        df = pd.concat((concat, df), axis=0)
        print(count, station, len(concat))
        count+=1

 - concat :  8760
0 BAR 1460
 - concat :  8760
1 ALU 1460
 - concat :  8760

/var/folders/7l/ltdxzx1s3dj_sz2kw6_5g8k00000gn/T/ipykernel_58901/2753830917.py:22: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat((concat, df), axis=0)

2 FLL 1460
 - concat :  8760
3 BGP 1460
 - concat :  8760
4 CDW 1460
 - concat :  8760
5 ASH 1460
 - concat :  8760
6 DLU 1460
 - concat :  8760
7 CMX 1460
 - concat :  8760
8 DAI 1460
 - concat :  8760
9 EAC 1460
 - concat :  8760
10 CLO 1460
 - concat :  8760
11 ECL 1460
 - concat :  8760
12 FAQ 1460
 - concat :  8760
13 FIN 1460
 - concat :  8760
14 BCK 1460
 - concat :  8760
15 MIS 1460
 - concat :  8760
16 MLP 1460
 - concat :  8760
17 PKM 1460
 - concat :  8760
18 PAR 1460
 - concat :  8760
19 KWA 1460
 - concat :  8760
20 MCQ 1460
 - concat :  8760
21 HRN 1460
 - concat :  8760
22 PYN 1460
 - concat :  8760
23 MOR 1460
 - concat :  8760
24 ING 1460
 - concat :  8760
25 KAA 1460
 - concat :  8760
26 NDE 1460
 - concat :  8760
27 NTY 1460
 - concat :  8760
28 HUR2 1460
 - concat :  8760
29 MOL 1460
 - concat :  8760
30 HFF 1460
 - concat :  8760
31 GOC 1460
 - concat :  8760
32 GOL2 1460
 - concat :  8760
33 JHL 1460
 - concat :  8760
34 UCE 1460
 - concat :  8760
35 WON 1460
 - concat :  8760
36 WAH 1460
 - concat :  8760
37 YXS 1460
 - concat :  8760
38 WZA 1460
 - concat :  8760
39 SHH 1460
 - concat :  8760
40 REC 1460
 - concat :  8760
41 YLW 1460
 - concat :  8760
42 RST 1460
 - concat :  8760
43 YGS 1460
 - concat :  8760
44 WOL 1460
 - concat :  8760
45 YZY 1460
 - concat :  8760
46 QIN2 1460
 - concat :  8760
47 YYD 1460
 - concat :  8760
48 WJR 1460
 - concat :  8760
49 STV 1460
 - concat :  8760
50 YRV 1460
 - concat :  8760
51 SBD2 1460

In [12]:
df.to_csv(f"{data_folder}/processed_bch_obs.csv")
df

                 UTC_DATE           x          y STN_ID  TEMP  PRECIP_AMOUNT
0     2023-01-01 00:00:00 -125.669800  50.093619   SBD2   1.5            NaN
6     2023-01-01 06:00:00 -125.669800  50.093619   SBD2  -0.8            0.0
12    2023-01-01 12:00:00 -125.669800  50.093619   SBD2  -1.3            0.2
18    2023-01-01 18:00:00 -125.669800  50.093619   SBD2   0.0            0.4
24    2023-01-02 00:00:00 -125.669800  50.093619   SBD2   0.8            0.3
...                   ...         ...        ...    ...   ...            ...
8730  2023-12-30 18:00:00 -118.351122  50.068553    BAR  -2.5            0.0
8736  2023-12-31 00:00:00 -118.351122  50.068553    BAR  -0.6            0.0
8742  2023-12-31 06:00:00 -118.351122  50.068553    BAR  -0.9            0.0
8748  2023-12-31 12:00:00 -118.351122  50.068553    BAR  -1.7            0.6
8754  2023-12-31 18:00:00 -118.351122  50.068553    BAR  -1.1            2.0

[75920 rows x 6 columns]

In [11]:
df.value_counts()

UTC_DATE             x            y          STN_ID  TEMP   PRECIP_AMOUNT
2023-01-01 06:00:00  -127.189444  54.823889  YYD     -4.9   0.0              1
2023-09-01 06:00:00  -118.225833  52.220556  MOL      6.3   7.5              1
                     -118.585940  52.053810  FLL      11.9  1.4              1
                     -118.596055  51.669195  GOL2     12.7  0.0              1
                     -118.619722  50.447222  PKM      6.2   0.0              1
                                                                            ..
2023-05-02 18:00:00  -123.896400  48.502678  BCK      17.8  0.0              1
                     -124.701444  55.785528  YGS      14.0  0.0              1
                     -125.073167  57.623333  KWA      10.3  0.0              1
                     -125.096111  49.643656  CMX      16.3  0.0              1
2023-12-31 18:00:00  -114.973675  49.447028  MOR     -0.5   0.1              1
Name: count, Length: 75862, dtype: int64